### ISSUE TITLE
[question] does it work with passwords?

### ISSUE THREAD

**Issue by Fuseteam** [univention/udm_import#6]
hi, i am looking to exports my existing users, password to import it at a later date

I managed to see all that i can list all the needed information with `udm users/user list` and as expected the password are properly hashed

can i use this import tool to import the users as is, without the users noticing anything changed?

we're having ldap issues with nextcloud (the users can seemingly just log in but this is out of scope for this repo, a pointer how we can debug this would be appreciated)
we would like to restore to an earlier backup ensure that the users password remain unchanged (just in case their password was changed after our latest backup)

**Comment by dansan** [comment]
Passwords should be exported directly from LDAP, because there are `3` of those that you want to backup and not all are available through UDM:

* `userPassword`
* `sambaNTPassword`
* `krb5Key`
* `krb5KeyVersionNumber`
* `sambaPwdLastSet`

You cannot neither read not write those values through UDM, so you cannot use this script for that. Sorry.

Use `ldapsearch` and `ldapadd` / `ldapmodify`.

**Comment by Fuseteam** [comment]
Cool, thanks for the tip. I'll look into `ldapsearch`, `ldapadd` and `ldapmodify` if there resource i could utilize to gain an understanding, i would appreciate a link
